# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0003_auto_20161212_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_width',
        ),
    ]
